apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
#          image: 855196134209.dkr.ecr.us-east-1.amazonaws.com/lecture-main/gateway:latest 
          image: username/gateway:latest
          ports:
            - containerPort: 8080
