apiVersion: apps/v1
kind: Deployment
metadata:
  name: course
  labels:
    app: course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
        - name: course
          image: 052937454741.dkr.ecr.ap-northeast-2.amazonaws.com/lecture-course:v0.1
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 1000m
